apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.cluster.internal:8200"
      path: "clinic-scheduler"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "clinic-scheduler"
          serviceAccountRef:
            name: "clinic-scheduler"
