apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinic-scheduler
  namespace: clinic-scheduler
  labels:
    app: clinic-scheduler
spec:
  selector:
    matchLabels:
      app: clinic-worker
  endpoints:
    - port: http
      path: /api/v1/metrics
      interval: 15s
      scrapeTimeout: 10s
